# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MemoryGame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher' , '3.6'
  pod 'Toast-Swift', '~> 2.0.0'
  pod 'SwiftLint'
  # Pods for MemoryGame

  target 'MemoryGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MemoryGameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
